services:
  mariaDB:
    container_name: shopping-db
    build:
      dockerfile: Dockerfile
      context: ./database
    image: shopping-db
    environment:
      - MARIADB_DATABASE=shopping
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
      - shopping-db-data:/var/lib/mysql # 데이터 영속성을 위한 볼륨
    ports:
      - "3307:3306"

volumes:
  shopping-db-data: